apiVersion: v1
kind: PersistentVolume
metadata: 
  name: faster-whisper-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /voice-assistant/pv/faster-whisper
  claimRef:
    name: faster-whisper-pvc
    namespace: voice-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faster-whisper-pvc
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-path