apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlc-telnet-deployment
  namespace: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlc-telnet
  template:
    metadata:
      labels:
        app: vlc-telnet
    spec:
      nodeSelector:
        kubernetes.io/hostname: bunnypi1
      containers:
        - name: vlc-telnet
          image: ne1ver/vlc-telnet:latest
          securityContext:
            privileged: true
          env: 
            - name: VLC_TELNET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vlc-telnet-password
                  key: password
            - name: ALSA_DEVICE
              valueFrom:
                configMapKeyRef:
                  name: alsa-device
                  key: alsa-device
          ports:
            - containerPort: 4212
          volumeMounts:
            - name: bunny-computer-device
              mountPath: /dev/snd
      restartPolicy: Always
      volumes:
        - name: bunny-computer-device
          hostPath:
            path: /dev/snd
            type: Directory
