apiVersion: v1
kind: Service
metadata:
  name: vlc-telnet-service
  namespace: music-assistant
spec:
  type: ClusterIP
  selector:
    app: vlc-telnet
  ports:
    - port: 4212
      targetPort: 4212
      name: vlc-telnet