apiVersion: v1
kind: PersistentVolume
metadata: 
  name: home-assistant-pv-time
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/localtime
  claimRef:
    name: home-assistant-pvc-time
    namespace: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc-time
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: home-assistant-pv-config
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /gen_cluster_fs/volumes/home-assistant/
  claimRef:
    name: home-assistant-pvc-config
    namespace: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path