apiVersion: v1
kind: PersistentVolume
metadata: 
  name: music-assistant-pv-data
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /music-assistant/pv/data
  claimRef:
    name: music-assistant-pvc-data
    namespace: music-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-pvc-data
  namespace: music-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path