apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdlp-pot-provider-deployment
  namespace: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytdlp-pot-provider
  template:
    metadata:
      labels:
        app: ytdlp-pot-provider
    spec:
      containers:
        - name: ytdlp-pot-provider
          # Referencing linux/arm64 platform image by manifest because of possible platform mismatch
          image: brainicism/bgutil-ytdlp-pot-provider@sha256:38361117f05500e1d26a8aee015b5fb52b46046cbdba88e3cbc8d1445e10b8f1
          ports:
            - containerPort: 4416