apiVersion: v1
kind: Service
metadata:
  name: ytdlp-pot-provider-service
  namespace: music-assistant
spec:
  type: ClusterIP
  selector:
    app: ytdlp-pot-provider
  ports:
    - port: 4416
      targetPort: 4416
      name: ytdlp-pot-provider