apiVersion: v1
kind: PersistentVolume
metadata: 
  name: speech-to-phrase-pv-models
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /voice-assistant/pv/models
  claimRef:
    name: speech-to-phrase-pvc-models
    namespace: voice-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-to-phrase-pvc-models
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: speech-to-phrase-pv-train
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /voice-assistant/pv/train
  claimRef:
    name: speech-to-phrase-pvc-train
    namespace: voice-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-to-phrase-pvc-train
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path
---