apiVersion: v1
kind: Service
metadata:
  name: speech-to-phrase-service
  namespace: voice-assistant
spec:
  type: ClusterIP
  selector:
    app: speech-to-phrase
  ports:
    - targetPort: 10300
      port: 10300
      name: speech-to-phrase-api