apiVersion: v1
kind: PersistentVolume
metadata: 
  name:  open-wake-word-pv-config
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /open-wake-word/pv/config
  claimRef:
    name: open-wake-word-pvc-config
    namespace: voice-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-wake-word-pvc-config
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name:  open-wake-word-pv-data
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /open-wake-word/pv/data
  claimRef:
    name: open-wake-word-pvc-data
    namespace: voice-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-wake-word-pvc-data
  namespace: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path